# zipcode search with page number and
POST 127.0.0.1:3000/search
Content-Type: application/json

{
  "searchQuery": "",
  "zipcode": "3011AA",
  "page": 2,
  "regions": [
    {
      "sectors": [],
      "regions": [
        {
          "title": "Drenthe",
          "filter": true
        }
      ],
      "shiftTypes": [
        {
          "title": "2 ploegendienst",
          "filter": true
        }
      ],
      "educationLevels": [
        {
          "title": "Basisonderwijs",
          "filter": true
        }
      ]
    }
  ]
}
