import searchResults from './results/data';

module.exports = {
  searchParams: {
    searchQuery: 'proces operator',
    zipcode: null,
    page: null,
    categories: [
      { title: 'Kwaliteit', hits: 91, filter: false },
      { title: 'Laboratorium', hits: 14, filter: false },
      { title: 'Manager', hits: 81, filter: false },
      { title: 'Monteur', hits: 122, filter: false },
      { title: 'Office', hits: 4, filter: false },
      { title: 'Planning', hits: 18, filter: false },
      { title: 'Procesoperator', hits: 847, filter: false },
      { title: 'Productie', hits: 81, filter: false },
    ],
    sectors: [
      { title: 'Kwaliteit', hits: 91, filter: false },
      { title: 'Laboratorium', hits: 14, filter: false },
      { title: 'Manager', hits: 81, filter: false },
      { title: 'Monteur', hits: 122, filter: false },
      { title: 'Office', hits: 4, filter: false },
      { title: 'Planning', hits: 18, filter: false },
      { title: 'Procesoperator', hits: 847, filter: false },
      { title: 'Productie', hits: 81, filter: false },
    ],
    regions: [
      { title: 'Drenthe', hits: 91, filter: false },
      { title: 'Laboratorium', hits: 14, filter: false },
      { title: 'Manager', hits: 81, filter: false },
      { title: 'Monteur', hits: 122, filter: false },
      { title: 'Office', hits: 4, filter: false },
      { title: 'Planning', hits: 18, filter: false },
      { title: 'Procesoperator', hits: 847, filter: false },
      { title: 'Productie', hits: 81, filter: false },
    ],
    shiftTypes: [
      { title: '2 ploegendienst', hits: 91, filter: false },
      { title: '3 ploegendienst', hits: 14, filter: false },
      { title: '4 ploegendienst', hits: 81, filter: false },
      { title: '5 ploegendienst', hits: 122, filter: false },
      { title: 'Office', hits: 4, filter: false },
      { title: 'Planning', hits: 18, filter: false },
      { title: 'Procesoperator', hits: 847, filter: false },
      { title: 'Productie', hits: 81, filter: false },
    ],
    educationLevels: [
      { title: 'Basisonderwijs', hits: 4, filter: false },
      { title: 'HAVO - VWO - MBO', hits: 18, filter: false },
      { title: 'HBO', hits: 847 },
      { title: 'LBO - VMBO - MAVO', hits: 81, filter: false },
    ],
  },
  results: searchResults,
};
