module.exports = {
    searchParams: {
        searchQuery: 'proces operator',
        zipcode: null,
        page: null,
        categories: [
            {title: 'Kwaliteit', amount: 91, filter: false},
            {title: 'Laboratorium', amount: 14, filter: false},
            {title: 'Manager', amount: 81, filter: false},
            {title: 'Monteur', amount: 122, filter: false},
            {title: 'Office', amount: 4, filter: false},
            {title: 'Planning', amount: 18, filter: false},
            {title: 'Procesoperator', amount: 847, filter: false},
            {title: 'Productie', amount: 81, filter: false},
        ],
        sectors: [
            {title: 'Kwaliteit', amount: 91, filter: false},
            {title: 'Laboratorium', amount: 14, filter: false},
            {title: 'Manager', amount: 81, filter: false},
            {title: 'Monteur', amount: 122, filter: false},
            {title: 'Office', amount: 4, filter: false},
            {title: 'Planning', amount: 18, filter: false},
            {title: 'Procesoperator', amount: 847, filter: false},
            {title: 'Productie', amount: 81, filter: false},
        ],
        regions: [
            {title: 'Drenthe', amount: 91, filter: false},
            {title: 'Laboratorium', amount: 14, filter: false},
            {title: 'Manager', amount: 81, filter: false},
            {title: 'Monteur', amount: 122, filter: false},
            {title: 'Office', amount: 4, filter: false},
            {title: 'Planning', amount: 18, filter: false},
            {title: 'Procesoperator', amount: 847, filter: false},
            {title: 'Productie', amount: 81, filter: false},
        ],
        shiftTypes: [
            {title: '2 ploegendienst', amount: 91, filter: false},
            {title: '3 ploegendienst', amount: 14, filter: false},
            {title: '4 ploegendienst', amount: 81, filter: false},
            {title: '5 ploegendienst', amount: 122, filter: false},
            {title: 'Office', amount: 4, filter: false},
            {title: 'Planning', amount: 18, filter: false},
            {title: 'Procesoperator', amount: 847, filter: false},
            {title: 'Productie', amount: 81, filter: false},
        ],
        educationLevels: [
            {title: 'Basisonderwijs', amount: 4, filter: false},
            {title: 'HAVO - VWO - MBO', amount: 18, filter: false},
            {title: 'HBO', amount: 847},
            {title: 'LBO - VMBO - MAVO', amount: 81, filter: false},
        ],
    },
    results: require('../searchResults/data')
}
